### ISSUE TITLE
16 &  64

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#1]
Problema en chrome de android con jugadores 16 y 64 ambos del equipo "wizards esports club"
https://twitter.com/LexW0lf/status/1092482128800034821

**Comment by wh0am1-dev** [comment]
Se necesita más info para empezar a hacer algo con esto. Lo cierro de momento, reabrimos esta misma issue, que estará en la sección de cerradas, en caso de que lo tengamos mas claro.

**Comment by salvelox** [comment]
https://twitter.com/LexW0lf/status/1092704080559030274

**Comment by salvelox** [comment]
Fijate en la imagen, en el 68 pone EMPERADOR cuando es KAISER el jugador, eso quiere decir que lo está traduciendo automáticamente, es posible que los números se pasen a letras por esto mismo...

**Comment by salvelox** [comment]
Confirmado que es el traductor,  misterio resuelto.
