### ISSUE TITLE
Jugadores no salen en la lista cuando si tiene partidas jugadas

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#11]
https://twitter.com/BorexRL/status/1100666367437668352
Dos ejemplos:
Borex: 76561198843064179
Sweeto: 76561198215794351

**Comment by salvelox** [comment]
![image](https://user-images.githubusercontent.com/5015471/53476215-1e448300-3a72-11e9-9c45-b52d75c4a5ae.png)
Ranked Standard está en posición 4 o 5 dependiendo del player.

**Comment by wh0am1-dev** [comment]
:rocket: closed by 500aed1eae10e8ec129c90b50f78760ebc23754d
