### ISSUE TITLE
Añadir FAQ

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#3]

**Comment by wh0am1-dev** [comment]
@salvelox si me consigues un número par de secciones / preguntas y respuestas, puede quedar perfe... yo creo que unas 4 o 6 sería lo ideal. Lo del número par es para que aparezcan en viewports grandes en varias columnas y no se vea cojo, que se vea bonito.

**Comment by salvelox** [comment]
@Neko250 ok!

**Comment by salvelox** [comment]
FAQ:
- Soy español pero no salgo en la lista, ¿Cómo puedo aparecer en ella?
Debes darle al botón "Peticiones" e indicar que quieres ser añadido a la lista.
- ¿Cuales son los requisitos para poder entrar en la lista?
Los requisitos son ser residente en España, estar por encima de 1000 de rating o ser una persona relevante dentro de la comunidad.
- ¿Cada cuanto se actualiza la lista?
La lista se actualiza diaria y automáticamente de madrugada.
- La información que aparece es errónea, no estoy en el equipo o mis redes sociales son incorrectas.
Debes darle al botón "Peticiones" e indicar el problema dando todos los detalles posibles.
- ¿Qué significan los números en verde o rojo debajo del rating?
Es la diferencia de puntos entre el día anterior y el actual.
- ¿Piensas añadir las colas de 1v1 y 2v2?
Una de nuestras prioridades es añadir estas colas en un futuro.

**Comment by wh0am1-dev** [comment]
🚀 closed by 3209528e660e7b0c1757a84f7f902aa04e23fa3d
