### ISSUE TITLE
Generar página de mantenimiento

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#4]
Para casos en los que la página se descontrole y no podamos arreglarla rápidamente.

**Comment by wh0am1-dev** [comment]
@salvelox te puedo montar un pequeño flag booleano en algún sitio del código que, cambiándolo entre `true` y `false`, ponga la página en modo "mantenimiento". Eso implicaría que, para activarlo, tendríamos que cambiar ese booleano y hacer `npm run build` y `npm run deploy`, para que se actualice el server. Dime qué te parece la idea.

**Comment by salvelox** [comment]
@Neko250 podría ser buena opción

**Comment by wh0am1-dev** [comment]
closed by da3126d6699532c219e133878c03b4e2fba0d65d
