### ISSUE TITLE
El jugador Kappa sale como icono para algunas personas

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#5]

**Comment by wh0am1-dev** [comment]
@salvelox pregúntales si usan algún plugin. Y, con respecto a lo de "algunas personas", ha sido a más de uno o a alguien aislado ?

**Comment by wh0am1-dev** [comment]
Esto lo voy a cerrar de momento también. Lo más probable es que pase lo mismo que con el traductor. Se reabre si se confirma que es un bug. (?)
