### ISSUE TITLE
Season 10 pero aparece rating de Season 9

### ISSUE THREAD

**Issue by salvelox** [Neko250/rlscrapper#6]
Hay que añadir una condición que indique que si no ha jugado ningún partido esta season no aparezca en la lista.

![image](https://user-images.githubusercontent.com/5015471/53301214-39d04380-3850-11e9-90e5-dba7c47ec9f8.png)
![image](https://user-images.githubusercontent.com/5015471/53301234-7734d100-3850-11e9-8c07-c680fb76c665.png)

**Comment by wh0am1-dev** [comment]
🚀  closed by 97c69cbaa840fca8e176792c970777c8c622efd3
